version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 8080:8000
  nginx-app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 4000:80
